[package]
name = "mutetra"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mutetra"
path = "src/main.rs"

[dependencies]
wgpu = "0.12"
winit = "0.26"
pollster = "0.2"
cgmath = "0.18"
bytemuck = { version = "1.19", features = ["derive"] }